Remove map elements with null value
Salazander/azure-osconfig pull request #14
Opened 2022-03-02 16:33 UTC by MagdaPaj

## Description

Fix deserialization of maps. Null values must be accepted. When map value is null, then the map element is deleted. 

## Checklist

- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-osconfig/blob/main/CONTRIBUTING.md).
- [ ] I added unit-tests to validate my changes. All unit tests are passing.
- [ ] I have merged the latest `main` branch prior to this PR submission.
- [ ] I submitted this PR against the `main` branch.

2022-03-03 08:12 UTC, Salazander requested changes

2022-03-03 08:12 UTC, Salazander commented on src/modules/packagemanagerconfiguration/src/lib/PackageManagerConfiguration.cpp
> +                    object.sources.erase(member.name.GetString());
I would recommend having the same behaviour when providing "" (empty string) and null as value.
This could easily be done by setting object.sources[member.name.GetString()] = "", right?

This would make life easier for the operator.

2022-03-03 10:36 UTC, syedhassaanahmed approved these changes

2022-03-04 05:50 UTC, Salazander approved these changes
looks good!

2022-03-04 07:48 UTC, merged