Add E2E tests for Pmc module
Salazander/azure-osconfig pull request #28
Opened 2022-03-28 15:52 UTC by MagdaPaj

## Description

Draft PR for adding E2E tests for Pmc module. I have some problems with async tests and await methods. When I run each test individually then it passes, but when I run them all together, then one of them fails. So I still need to fix it.
It would be nice to have one test code with multiple tests cases.

## Checklist

- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-osconfig/blob/main/CONTRIBUTING.md).
- [ ] I added unit-tests to validate my changes. All unit tests are passing.
- [ ] I have merged the latest `main` branch prior to this PR submission.
- [ ] I submitted this PR against the `main` branch.

2022-03-29 06:24 UTC, Salazander requested changes

2022-03-29 06:24 UTC, Salazander commented on src/tests/e2etest/PmcTests.cs
> +            desiredTask.Wait();
Use 'await' for every method returning a Task, mixing blocking Wait() and async await is almost never a good idea.
https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

2022-03-29 06:24 UTC, Salazander commented on src/tests/e2etest/PmcTests.cs
> +                    {_sourceName, "deb [arch=amd64,arm64,ppc64el] http://mirror.mephi.ru/mariadb/repo/10.5/ubuntu focal main"}
Err:5 http://mirror.mephi.ru/mariadb/repo/10.5/ubuntu focal InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F1656F24C74CD1D8
Reading package lists... Done
W: GPG error: http://mirror.mephi.ru/mariadb/repo/10.5/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F1656F24C74CD1D8
E: The repository 'http://mirror.mephi.ru/mariadb/repo/10.5/ubuntu focal InRelease' is not signed.

Can you replace it with a EU-based mirror with https?

2022-03-29 06:24 UTC, Salazander commented on src/tests/e2etest/PmcTests.cs
> +                Assert.IsNotNull(reported.Packages.FirstOrDefault(x => x.StartsWith(_correctPackageName + "=")));
Consider using string interpolation instead $"{_correctPackageName}="

2022-03-30 12:17 UTC, syedhassaanahmed commented on src/tests/e2etest/PmcTests.cs
> +                    {_sourceName, "deb [arch=amd64,arm64,ppc64el] http://mirror.mephi.ru/mariadb/repo/10.5/ubuntu focal main"}
How about a US-based mirror (West Coast)? I'm thinking the OSConfig team would be the one mostly running these tests in their environment and their Azure resources are likely hosted in West US.

2022-03-30 12:20 UTC, syedhassaanahmed commented on src/tests/e2etest/PmcTests.cs
> +            Regex uninstalledPackagePattern = new Regex($"{_packageNameToUninstall}=\\(none\\)");
Nit: Consider using `var` on the left side as the type (`Regex`) is already inferred from the right side.

2022-03-30 13:38 UTC, Ioana37 commented on src/tests/e2etest/PmcTests.cs
> +
Nit: Remove empty line.

2022-03-30 13:56 UTC, MagdaPaj commented on src/tests/e2etest/PmcTests.cs
> +                    {_sourceName, "deb [arch=amd64,arm64,ppc64el] http://mirror.mephi.ru/mariadb/repo/10.5/ubuntu focal main"}
I can go with US-based mirror, not sure which one is West Coast. Full list is here: https://mirmon.mariadb.org/. For example I could use this
```
deb [trusted=yes] https://mirrors.gigenet.com/mariadb/repo/10.5/ubuntu focal main
```

Important things:
* I need to specify `[trusted=yes]`, because for the moment we don't have GPG keys configuration. And if I don't specify it, then apt-get update fails. With `[trusted=yes]` it returns warning but doesn't fail. That's not ideal, but not sure what could we do differently.
* When setting the source I'm specifying that it is for Ubuntu and for focal release. But E2E tests are executed on different  distros (see [here](https://github.com/Salazander/azure-osconfig/blob/main/devops/pipeline/e2etest.yaml#L230-L240)). So I need to find a way to not execute our tests on distros different than debian. But what about specifying the release? Should I do that dynamically? (meaning: detect what is the release (focal, bionic, etc) and then specify that in the source). What would be your suggestions?

2022-03-30 18:02 UTC, syedhassaanahmed commented on src/tests/e2etest/PmcTests.cs
> +                    {_sourceName, "deb [arch=amd64,arm64,ppc64el] http://mirror.mephi.ru/mariadb/repo/10.5/ubuntu focal main"}
- The gigenet mirror looks good. 
- The `[trusted=yes]` is going to be temporary until we implement the GPG keys configuration right? In that case the warning should be fine for now.
- When setting the source, we could specify the release dynamically for the current list of distros specified in the AzDO pipeline job matrix (Debian 9, Ubuntu 18 and Ubuntu 20). In bash we can get the release with `cat /etc/issue`. There are also [other ways](https://unix.stackexchange.com/a/35190) but this one is the only one that works in WSL correctly. This bash call can be wrapped in a C# method like [this](https://stackoverflow.com/a/56275049).

2022-03-31 16:50 UTC, MagdaPaj commented on src/tests/e2etest/PmcTests.cs
> +                    {_sourceName, "deb [arch=amd64,arm64,ppc64el] http://mirror.mephi.ru/mariadb/repo/10.5/ubuntu focal main"}
I've pushed one more commit, where I introduced a dictionary for mapping an OS distro to correct source value. 

Originally we said to use existing env var `"E2E_OSCONFIG_DEVICE_ID"`, but that somehow doesn't feel correct, specially when you want to run tests locally. Because then the device id for sure won't be like distro name.

So I'm proposing to introduce a new env var `E2E_OSCONFIG_DISTRIBUTION_NAME`. It should be rather easy to introduce this env var in E2E pipelines. For the moment I'm not modifying any pipeline, because I see that there is an open PR for that. But there is a [`distroName` parameter](https://github.com/Azure/azure-osconfig/pull/148/files#diff-e98e8c08cc91101d1d94c685c7ef11cb7388a2086685ed586ae3878629d8db53R4), so I think we will be able to reuse that and assign it to the env var that will be passed to the tests.

Let me know how do you see it. Any suggestion more than welcome.

2022-03-31 16:50 UTC, syedhassaanahmed commented on src/tests/e2etest/PmcTests.cs
> +                Assert.Ignore("Unable to determine OS distribution. Missing environment variable: E2E_OSCONFIG_DISTRIBUTION_NAME");
Nit: Can we make the env var string "E2E_OSCONFIG_DISTRIBUTION_NAME" a constant?

2022-03-31 16:51 UTC, syedhassaanahmed approved these changes

2022-04-01 05:03 UTC, Salazander approved these changes
:+1:

2022-04-01 06:53 UTC, merged