Feature/track packages
Salazander/azure-osconfig pull request #6
Opened 2022-01-26 15:59 UTC by Ioana37

## Description

*Describe your changes in as much detail as possible. Provide a link/reference to the issue solved with this request if any.*

## Checklist

- [ ] I have read the [contribution guidelines](https://github.com/Azure/azure-osconfig/blob/main/CONTRIBUTING.md).
- [ ] I added unit-tests to validate my changes. All unit tests are passing.
- [ ] I have merged the latest `main` branch prior to this PR submission.
- [ ] I submitted this PR against the `main` branch.

2022-01-28 08:08 UTC, Salazander requested changes
Looks good - only very small changes needed

2022-01-28 10:44 UTC, MagdaPaj commented on src/modules/aptinstall/src/lib/AptInstall.cpp
> +        std::vector<std::string> result = Split(packagesLine, " ");
Yes, it does. The function extracts all elements from the string that are not whitespaces, and puts them in a vector. So it doesn't matter if there is one or more whitespaces (or any other delimiter).

2022-01-28 10:47 UTC, MagdaPaj commented on src/modules/aptinstall/src/lib/AptInstall.cpp
> +std::vector<std::string> AptInstallBase::Split(const std::string& str, const std::string& delimiter)
We've just had a look at it. But it seems to be suitable for extracting strings when reading from a console (istream). We just deal with normal string, so does it make any sense to perform additional conversions?

2022-01-28 10:56 UTC, MagdaPaj commented on src/modules/aptinstall/src/lib/AptInstall.h
> +        ExecutionState executionState;
We think that 'Unknown' is a better state as the initialization state. 'Successful' should be used only when the execution of desired property was done successfully. There is a similar approach with the CommandState in the CommandRunner module. And it could be a bit dangerous to use 'Successful' as a default state (in case something unexpected happens).

2022-01-28 11:37 UTC, MagdaPaj commented on src/modules/aptinstall/src/lib/AptInstall.cpp
> +        std::string version = rawVersion != "" ? Split(rawVersion, ":")[1] : "(failed)";
We noticed that user may specify a package that doesn't exist. So in this case our command ` apt-cache policy foo | grep Installed` will return nothing. But we anyway want to report it under reported properties. So we propose to return `(failed)`. And this is an example:
`"Packages":{"bar":"1.11.1-3","cowsay":"3.03+dfsg2-7","foo":"(failed)","sl":"(none)"}`

WDYT?

2022-01-31 10:09 UTC, syedhassaanahmed approved these changes

2022-01-31 10:33 UTC, merged